;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Shared settings for all ESP32 environments
[esp32_base]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600

; no different settings from default environment
[env:cable]
extends = esp32_base
; upload_port is set through environment variable

; environment for over the air updates
[env:ota]
extends = esp32_base
upload_protocol = espota
upload_flags =
  --port=3232
  --auth=secretpw0

; environment for debugging (using JTAG)
[env:debug]
extends = esp32_base
build_type = debug
upload_speed = 921600
debug_tool = minimodule
build_flags = -DDEBUG_JTAG

; native environment for unit tests on host PC
[env:native]
platform = native
build_flags =
  -I test/mocks
  -include Arduino.h
  -DCONF_MAITE
  -std=c++11
  -DWLAN_SSID=\"test\"
  -DWLAN_PSK=\"test\"
  -DESP_IP=192,168,1,1
build_src_filter = +<*> -<main.cpp> -<ota.cpp> -<buttons.cpp>
test_build_src = yes
test_framework = unity
test_ignore = mocks
