wireplumber.profiles = {
  main = {
    monitor.bluez.seat-monitoring = disabled
    hardware.bluetooth = required
  }
}

wireplumber.components = [
  {
    name = monitors/bluez.lua, type = script/lua
    provides = monitor.bluez
    requires = [ support.export-core,
                 pw.client-device,
                 pw.client-node,
                 pw.node-factory.adapter ]
  }
]
