monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.platform-soc_sound.stereo-fallback" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
      }
    }
  }
]
