wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = true
        bluez5.profile = "audio-gateway"
      }
    }
  }
]
