---
- name: Updating Package Index
  apt:
    update_cache: yes

- name: Upgrading Packages
  apt:
    name: "*"
    state: latest

- name: Installing Basic Packages
  apt:
    pkg:
      - btop
      - git
      - vim
