---
- name: Updating Package Index
  apt:
    update_cache: yes

- name: Upgrading Packages
  apt:
    name: "*"
    state: latest

- name: Installing Basic Packages
  apt:
    pkg:
      - python3-pip
      - python3-pyaudio
      - python3-numpy
      - python3-serial
      - pipx

- name: Installing platformio
  shell: pipx install platformio
  args:
    creates: /root/.local/bin/platformio

- name: Cloning Git Repository ledding
  git:
    repo: 'https://github.com/superbjorn09/ledding'
    dest: /home/{{ deploy_user }}/ledding
    force: yes

- name: Setting up permissions
  file:
    path: /home/{{ deploy_user }}/ledding
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    recurse: yes

- name: Install Systemd Unit for AudioFFT
  template:
    src: templates/pyaudio.service
    dest: /etc/systemd/system/

- name: Enable and restart Systemd Unit
  systemd:
    state: restarted
    name: pyaudio.service
    enabled: yes
    daemon_reload: yes

- name: Removing unused packages
  apt:
    autoremove: yes
    purge: yes
