---
- name: Installing Basic Packages
  apt:
    pkg:
      - python3-pip
      - python3-pyaudio
      - python3-numpy
      - python3-serial

- name: Updating Git Repository ledding
  git:
    repo: 'https://github.com/superbjorn09/ledding'
    dest: /home/{{ deploy_user }}/ledding
    update: yes
    force: yes
    version: master

- name: Setting up permissions
  file:
    path: /home/{{ deploy_user }}/ledding
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    recurse: yes

- name: Install Systemd Unit for AudioFFT
  template:
    src: templates/pyaudio.service
    dest: /etc/systemd/system/

- name: Enable and restart Systemd Unit
  systemd:
    state: restarted
    name: pyaudio.service
    enabled: yes
    daemon_reload: yes

- name: Add deploy user to dialout group
  user:
    name: "{{ deploy_user }}"
    groups: dialout
    append: yes

- name: Set ttyS0 group to dialout via udev rule
  copy:
    dest: /etc/udev/rules.d/99-ttyS0.rules
    content: 'KERNEL=="ttyS0", GROUP="dialout", MODE="0660"'

- name: Apply udev rules
  command: udevadm trigger --subsystem-match=tty

- name: Disable serial getty on ttyS0
  systemd:
    name: serial-getty@ttyS0.service
    enabled: no
    state: stopped

- name: Enable UART in /boot/firmware/config.txt
  lineinfile:
    path: /boot/firmware/config.txt
    line: enable_uart=1
    state: present

- name: Removing unused packages
  apt:
    autoremove: yes
    purge: yes
